import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "module";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const outdir = process.env.PLUGIN_DIR || ".";

// Garante que o diretório de saída e a pasta do cofre existam antes da compilação
if (outdir !== "." && outdir !== "") {
    fs.mkdirSync(outdir, { recursive: true });
}
if (fs.existsSync("tmdb-vault/.obsidian/plugins")) {
    fs.mkdirSync("tmdb-vault/.obsidian/plugins/search-movies-tv-tmdb", { recursive: true });
}

const context = await esbuild.context({
    banner: { js: banner },
    entryPoints: ["main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: `${outdir}/main.js`,
    minify: false,
});

function copyPluginAssets() {
    const targetDirs = new Set();
    if (outdir !== "." && outdir !== "") {
        targetDirs.add(outdir);
    }
    if (fs.existsSync("tmdb-vault/.obsidian/plugins")) {
        targetDirs.add("tmdb-vault/.obsidian/plugins/search-movies-tv-tmdb");
    }

    for (const dir of targetDirs) {
        fs.mkdirSync(dir, { recursive: true });

        // Copia main.js para o diretório de destino se necessário
        if (fs.existsSync(`${outdir}/main.js`) && `${outdir}/main.js` !== `${dir}/main.js`) {
            fs.copyFileSync(`${outdir}/main.js`, `${dir}/main.js`);
        } else if (fs.existsSync("main.js") && "main.js" !== `${dir}/main.js`) {
            fs.copyFileSync("main.js", `${dir}/main.js`);
        }
        if (fs.existsSync("manifest.json")) {
            fs.copyFileSync("manifest.json", `${dir}/manifest.json`);
        }
        if (fs.existsSync("styles.css")) {
            fs.copyFileSync("styles.css", `${dir}/styles.css`);
        }
        // Ativa o hot-reload para facilitar desenvolvimento local
        fs.writeFileSync(`${dir}/.hotreload`, "");
    }
}

if (prod) {
    await context.rebuild();
    copyPluginAssets();
    process.exit(0);
} else {
    copyPluginAssets();
    await context.watch();
}
